import { AlertCircle, CheckCircle2, Circle, FileText, XCircle } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { ReviewScorecardInput, ScoreDecision, ScorecardRow } from '@/app/contracts'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'
const Mobile = ({ children }: { children: string }) => <span className="mr-1 sm:hidden">{children}</span>
function Decision({ value }: { value: ScoreDecision | null }) { const text = value === 'positive' ? '긍정' : value === 'negative' ? '부정' : value === 'recorded' ? '기록' : '미검토'; const Icon = value === 'positive' ? CheckCircle2 : value === 'negative' ? XCircle : value === 'recorded' ? FileText : Circle; return <span className="inline-flex items-center gap-1"><Icon aria-hidden="true" className="size-4" data-testid="decision-icon" />{text}</span> }
export function ScorecardReview({ interviewId, scorecard, onReview }: { interviewId: string; scorecard: ScorecardRow[]; onReview: (input: ReviewScorecardInput) => Promise<boolean> }) {
 const [selected,setSelected]=useState<ScorecardRow|null>(null); const [decision,setDecision]=useState<Exclude<ScoreDecision,'recorded'>|null>(null); const [rationale,setRationale]=useState(''); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const mounted=useRef(false); const lock=useRef(false); const generation=useRef(0)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current+=1}},[])
 const clear=()=>{generation.current+=1;setSelected(null);setDecision(null);setRationale('');setError(null)}
 async function submit(input:ReviewScorecardInput, close:boolean){if(lock.current)return;lock.current=true;const g=++generation.current;setBusy(true);setError(null);try{if(await onReview(input)){if(mounted.current&&g===generation.current&&close)clear()}}catch{if(mounted.current&&g===generation.current)setError('검토를 저장하지 못했습니다')}finally{if(g===generation.current){lock.current=false;if(mounted.current)setBusy(false)}}}
 const override=()=>{if(!selected||!decision)return;const text=rationale.trim();if(!text){setError('근거를 입력하세요');return}void submit({interviewId,questionId:selected.questionId,action:'override',expertStatus:decision,rationale:text},true)}
 const action='h-auto min-h-11 min-w-11 sm:min-h-8 sm:min-w-0'
 return <><Table aria-label="점수표"><TableHeader className="sr-only sm:not-sr-only sm:table-header-group"><TableRow><TableHead>문항</TableHead><TableHead>값</TableHead><TableHead>AI 판정</TableHead><TableHead>전문가 판정</TableHead><TableHead>작업</TableHead></TableRow></TableHeader><TableBody className="block sm:table-row-group">{scorecard.map(r=><TableRow className="block sm:table-row" key={r.questionId}><TableCell className="block break-words whitespace-normal sm:table-cell"><Mobile>문항:</Mobile>{r.questionId}<span className="ml-2 break-words text-muted-foreground">{r.question}</span></TableCell><TableCell className="block break-words whitespace-normal sm:table-cell"><Mobile>값:</Mobile>{r.value??'없음'}</TableCell><TableCell className="block sm:table-cell"><Mobile>AI:</Mobile><Decision value={r.aiStatus}/></TableCell><TableCell className="block sm:table-cell"><Mobile>전문가:</Mobile><Decision value={r.expertStatus}/></TableCell><TableCell className="block sm:table-cell"><Mobile>작업:</Mobile><Button aria-label={`${r.questionId} 동의`} className={action} disabled={busy} onClick={()=>void submit({interviewId,questionId:r.questionId,action:'approve'},false)} size="sm" type="button" variant="outline">동의</Button><Button aria-label={`${r.questionId} 변경`} className={action} disabled={busy} onClick={()=>{setSelected(r);setDecision(r.aiStatus==='positive'||r.aiStatus==='negative'?r.aiStatus:null);setError(null)}} size="sm" type="button" variant="outline">변경</Button></TableCell></TableRow>)}</TableBody></Table>{error&&!selected&&<p role="alert">{error}</p>}<Dialog onOpenChange={o=>!o&&clear()} open={!!selected}><DialogContent><DialogHeader><DialogTitle>판정 변경</DialogTitle></DialogHeader><label><input checked={decision==='positive'} name="decision" onChange={()=>setDecision('positive')} type="radio"/>긍정</label><label><input checked={decision==='negative'} name="decision" onChange={()=>setDecision('negative')} type="radio"/>부정</label><Label htmlFor="review-rationale">근거</Label><Textarea aria-describedby={error?'review-rationale-error':undefined} aria-invalid={!!error} aria-required="true" id="review-rationale" onChange={e=>setRationale(e.target.value)} required value={rationale}/>{error&&<p id="review-rationale-error" role="alert"><AlertCircle aria-hidden="true"/>{error}</p>}<DialogFooter><Button onClick={clear} type="button" variant="outline">취소</Button><Button disabled={busy||!decision} onClick={override} type="button">저장</Button></DialogFooter></DialogContent></Dialog></>
}
