# Streamlit Secrets 템플릿
# 이 파일을 복사하여 secrets.toml로 만들고 실제 값으로 대체하세요

[admin]
username = "your_admin_username"
password = "your_admin_password"

[env]
GOOGLE_API_KEY = "your_gemini_api_key_here"
LANGSMITH_API_KEY = "your_langsmith_key_here"
LANGSMITH_TRACING = false
LANGSMITH_PROJECT = "project_name"
LOG_LEVEL = "INFO"
MAX_CLARIFICATIONS = 3

# 사용법:
# 1. 이 파일을 .streamlit/secrets.toml로 복사
# 2. 각 값을 실제 값으로 대체
# 3. secrets.toml은 .gitignore에 포함되어 Git에 커밋되지 않음
#
# 참고: Ploomber Cloud 배포 시에는 환경변수를
# 클라우드 플랫폼의 Secrets 섹션에서 설정해야 합니다